steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-django-app:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-django-app:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-django-app'
      - '--image=gcr.io/$PROJECT_ID/my-django-app:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

# Substitute variables: COMMIT_SHA and PROJECT_ID
substitutions:
  _PROJECT_ID: 'bigdata3844'

images:
  - 'gcr.io/$PROJECT_ID/my-django-app:$COMMIT_SHA'

timeout: '1200s'
